import { useEffect, useState } from 'react';
import { Alert, ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import Icon from '../components/Icon';
import { adminApi } from '../api';
import { colors } from '../theme';

export default function AdminUsersScreen({ navigation, token }) {
  const [users, setUsers] = useState(null);
  const [editing, setEditing] = useState(null);
  const [form, setForm] = useState({ name: '', email: '' });
  const load = async () => setUsers((await adminApi.users(token)).users);
  useEffect(() => { load(); }, []);
  const save = async () => { if (!form.name.trim() || !form.email.trim()) return Alert.alert('Datos incompletos', 'Nombre y email son obligatorios.'); await adminApi.updateUser(editing.id, form, token); setEditing(null); load(); };
  const remove = (user) => Alert.alert('Eliminar usuario', `¿Quieres eliminar a ${user.name}?`, [{ text: 'Cancelar' }, { text: 'Eliminar', style: 'destructive', onPress: async () => { await adminApi.deleteUser(user.id, token); load(); } }]);
  if (!users) return <SafeAreaView style={styles.safeArea}><ActivityIndicator color={colors.lime} style={styles.loader} /></SafeAreaView>;
  return <SafeAreaView style={styles.safeArea}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => navigation.goBack()}><Icon name="arrow-left" size={22} color={colors.white} /></Pressable><View><Text style={styles.kicker}>ADMINISTRACIÓN</Text><Text style={styles.title}>Usuarios</Text></View><View style={styles.count}><Text style={styles.countText}>{users.length}</Text></View></View>{editing && <View style={styles.form}><Text style={styles.formTitle}>Editar usuario</Text><TextInput value={form.name} onChangeText={(name) => setForm({ ...form, name })} placeholder="Nombre" placeholderTextColor={colors.muted} style={styles.input} /><TextInput value={form.email} onChangeText={(email) => setForm({ ...form, email })} placeholder="Email" placeholderTextColor={colors.muted} autoCapitalize="none" keyboardType="email-address" style={styles.input} /><View style={styles.formActions}><Pressable onPress={() => setEditing(null)}><Text style={styles.cancel}>Cancelar</Text></Pressable><Pressable style={styles.save} onPress={save}><Text style={styles.saveText}>Guardar cambios</Text></Pressable></View></View>}{users.map((user) => <View key={user.id} style={styles.row}><View style={styles.avatar}><Text style={styles.avatarText}>{user.name.slice(0, 1).toUpperCase()}</Text></View><View style={styles.info}><Text style={styles.name}>{user.name}</Text><Text style={styles.email}>{user.email}</Text></View><Pressable style={styles.rowButton} onPress={() => { setEditing(user); setForm({ name: user.name, email: user.email }); }}><Icon name="edit" size={19} color={colors.purpleBright} /></Pressable><Pressable style={styles.rowButton} onPress={() => remove(user)}><Icon name="delete-outline" size={19} color={colors.danger} /></Pressable></View>)}</ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safeArea: { flex: 1, backgroundColor: colors.background }, loader: { flex: 1 }, content: { padding: 18, paddingBottom: 35 }, header: { flexDirection: 'row', alignItems: 'center', gap: 13, marginTop: 12, marginBottom: 23 }, kicker: { color: colors.purpleBright, fontSize: 10, fontWeight: '900', letterSpacing: 1.3 }, title: { color: colors.white, fontSize: 28, fontWeight: '900', marginTop: 4 }, count: { marginLeft: 'auto', backgroundColor: colors.lime, minWidth: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, countText: { color: colors.background, fontWeight: '900' }, row: { backgroundColor: colors.card, borderRadius: 15, padding: 13, flexDirection: 'row', alignItems: 'center', marginBottom: 10, borderWidth: 1, borderColor: colors.line }, avatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.purple, alignItems: 'center', justifyContent: 'center', marginRight: 11 }, avatarText: { color: colors.white, fontWeight: '900', fontSize: 16 }, info: { flex: 1 }, name: { color: colors.white, fontSize: 13, fontWeight: '800' }, email: { color: colors.muted, fontSize: 11, marginTop: 4 }, rowButton: { padding: 9 }, form: { backgroundColor: colors.surface, borderRadius: 16, padding: 15, marginBottom: 16, borderWidth: 1, borderColor: colors.purpleBright }, formTitle: { color: colors.white, fontSize: 15, fontWeight: '900', marginBottom: 9 }, input: { height: 45, color: colors.white, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.line, borderRadius: 10, paddingHorizontal: 12, marginTop: 8 }, formActions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 15, marginTop: 13 }, cancel: { color: colors.muted, fontWeight: '800' }, save: { backgroundColor: colors.lime, borderRadius: 10, paddingHorizontal: 13, paddingVertical: 10 }, saveText: { color: colors.background, fontWeight: '900', fontSize: 11 } });
