import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import Icon from '../components/Icon';
import BottomNav from '../components/BottomNav';
import { colors, formatPrice } from '../theme';

export default function CartScreen({ cart, onRemove, navigation, user }) {
  if (!user) return <SafeAreaView style={styles.safeArea}><View style={styles.empty}><Icon name="cart-lock" size={55} color={colors.purpleBright} /><Text style={styles.emptyTitle}>Inicia sesión para usar tu carrito</Text><Text style={styles.emptyText}>Necesitas una cuenta para añadir productos y comprar.</Text><Pressable style={styles.primary} onPress={() => navigation.navigate('Login')}><Text style={styles.primaryText}>Iniciar sesión</Text></Pressable></View><BottomNav active="cart" navigation={navigation} cartCount={0} /></SafeAreaView>;
  const total = cart.reduce((sum, item) => sum + item.price, 0);
  return <SafeAreaView style={styles.safeArea}><ScrollView contentContainerStyle={styles.content}><Text style={styles.kicker}>TU SELECCIÓN</Text><Text style={styles.title}>Carrito</Text>{cart.length === 0 ? <View style={styles.empty}><Icon name="cart-off" size={55} color={colors.purpleBright} /><Text style={styles.emptyTitle}>Tu carrito está vacío</Text><Text style={styles.emptyText}>Añade algo increíble a tu setup.</Text><Pressable style={styles.primary} onPress={() => navigation.navigate('Main', { screen: 'home' })}><Text style={styles.primaryText}>Explorar productos</Text></Pressable></View> : <><Text style={styles.count}>{cart.length} producto{cart.length > 1 ? 's' : ''}</Text>{cart.map((item, index) => <View style={styles.item} key={`${item.id}-${index}`}><Image source={{ uri: item.image }} style={styles.image} /><View style={styles.info}><Text style={styles.name}>{item.shortName}</Text><Text style={styles.category}>{item.categoryLabel}</Text><Text style={styles.price}>{formatPrice(item.price)}</Text></View><Pressable onPress={() => onRemove(index)} accessibilityLabel="Eliminar producto"><Icon name="trash-can-outline" size={21} color={colors.muted} /></Pressable></View>)}<View style={styles.summary}><View style={styles.row}><Text style={styles.label}>Subtotal</Text><Text style={styles.value}>{formatPrice(total)}</Text></View><View style={styles.row}><Text style={styles.label}>Envío</Text><Text style={styles.free}>GRATIS</Text></View><View style={[styles.row, styles.totalRow]}><Text style={styles.totalLabel}>Total</Text><Text style={styles.total}>{formatPrice(total)}</Text></View><Pressable style={styles.primary} onPress={() => navigation.navigate('Checkout')}><Text style={styles.primaryText}>Continuar compra</Text><Icon name="arrow-right-circle" size={19} color={colors.background} /></Pressable></View></>}</ScrollView><BottomNav active="cart" navigation={navigation} cartCount={cart.length} /></SafeAreaView>;
}

const styles = StyleSheet.create({ safeArea: { flex: 1, backgroundColor: colors.background }, content: { padding: 18, paddingBottom: 105 }, kicker: { color: colors.purpleBright, fontSize: 10, fontWeight: '900', letterSpacing: 1.4, marginTop: 12 }, title: { color: colors.white, fontSize: 32, fontWeight: '900', marginTop: 5 }, count: { color: colors.muted, fontSize: 12, marginVertical: 16 }, empty: { alignItems: 'center', paddingTop: 90 }, emptyTitle: { color: colors.white, fontSize: 19, fontWeight: '900', marginTop: 15 }, emptyText: { color: colors.muted, fontSize: 13, marginTop: 6 }, primary: { minHeight: 49, paddingHorizontal: 20, borderRadius: 14, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 9, marginTop: 25 }, primaryText: { color: colors.background, fontSize: 13, fontWeight: '900' }, item: { backgroundColor: colors.card, borderRadius: 16, padding: 12, flexDirection: 'row', alignItems: 'center', marginBottom: 10 }, image: { width: 70, height: 70, borderRadius: 10, backgroundColor: colors.surfaceLight }, info: { flex: 1, marginLeft: 13 }, name: { color: colors.white, fontSize: 14, fontWeight: '800' }, category: { color: colors.purpleBright, fontSize: 10, marginTop: 5 }, price: { color: colors.white, fontSize: 16, fontWeight: '900', marginTop: 7 }, summary: { backgroundColor: colors.card, borderRadius: 17, padding: 17, marginTop: 12 }, row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 }, label: { color: colors.muted, fontSize: 13 }, value: { color: colors.white, fontSize: 13, fontWeight: '700' }, free: { color: colors.lime, fontSize: 11, fontWeight: '900' }, totalRow: { borderTopWidth: 1, borderTopColor: colors.line, paddingTop: 15, marginTop: 3 }, totalLabel: { color: colors.white, fontSize: 16, fontWeight: '900' }, total: { color: colors.white, fontSize: 20, fontWeight: '900' } });
