import { useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import Icon from '../components/Icon';
import { colors, formatPrice } from '../theme';

export default function ProductScreen({ route, navigation, onAdd, onBuyNow }) {
  const { product } = route.params;
  const [activeImage, setActiveImage] = useState(0);
  return <SafeAreaView style={styles.safeArea}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><Pressable style={styles.back} onPress={() => navigation.goBack()}><Icon name="arrow-left" size={21} /></Pressable><Text style={styles.headerTitle}>Producto</Text><Icon name="share-variant-outline" size={21} color={colors.muted} /></View>
    <Image source={{ uri: product.gallery[activeImage] }} style={styles.mainImage} resizeMode="cover" /><View style={styles.gallery}>{product.gallery.map((image, index) => <Pressable key={image} onPress={() => setActiveImage(index)} style={[styles.thumb, index === activeImage && styles.activeThumb]}><Image source={{ uri: image }} style={styles.thumbImage} resizeMode="cover" /></Pressable>)}</View>
    <Text style={styles.category}>{product.categoryLabel.toUpperCase()}</Text><Text style={styles.title}>{product.name}</Text><View style={styles.rating}><Icon name="star" size={16} color={colors.lime} /><Text style={styles.ratingText}>{product.rating} · 38 opiniones</Text><Text style={styles.stock}>EN STOCK</Text></View><View style={styles.priceRow}><Text style={styles.price}>{formatPrice(product.price)}</Text>{product.oldPrice && <Text style={styles.oldPrice}>{formatPrice(product.oldPrice)}</Text>}</View><Text style={styles.installments}>6 cuotas sin interés con tarjetas seleccionadas</Text>
    <View style={styles.divider} /><Text style={styles.sectionTitle}>Descripción</Text><Text style={styles.description}>{product.description}</Text><View style={styles.specs}>{product.specs.map((spec) => <View style={styles.spec} key={spec}><Icon name="check-circle-outline" size={17} color={colors.purpleBright} /><Text style={styles.specText}>{spec}</Text></View>)}</View><View style={styles.delivery}><Icon name="truck-fast-outline" size={24} color={colors.lime} /><View><Text style={styles.deliveryTitle}>Envío gratis</Text><Text style={styles.deliveryText}>Recíbelo mañana en tu domicilio</Text></View></View>
  </ScrollView><View style={styles.actions}><Pressable style={styles.buy} onPress={() => onBuyNow(product)}><Text style={styles.buyText}>Comprar ahora</Text></Pressable><Pressable style={styles.add} onPress={() => onAdd(product)} accessibilityLabel="Añadir al carrito"><Icon name="cart-plus" size={22} color={colors.background} /></Pressable></View></SafeAreaView>;
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background }, content: { padding: 18, paddingBottom: 110 }, header: { height: 58, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, headerTitle: { color: colors.white, fontSize: 14, fontWeight: '900' }, back: { width: 40, height: 40, borderRadius: 14, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' }, mainImage: { width: '100%', height: 300, borderRadius: 21, backgroundColor: colors.surface }, gallery: { flexDirection: 'row', gap: 10, marginVertical: 17 }, thumb: { width: 63, height: 63, borderRadius: 11, opacity: 0.5, overflow: 'hidden' }, activeThumb: { opacity: 1, borderWidth: 2, borderColor: colors.lime }, thumbImage: { width: '100%', height: '100%' }, category: { color: colors.purpleBright, fontSize: 10, fontWeight: '900', letterSpacing: 1, marginBottom: 7 }, title: { color: colors.white, fontSize: 27, lineHeight: 31, fontWeight: '900' }, rating: { flexDirection: 'row', alignItems: 'center', marginTop: 10 }, ratingText: { color: colors.muted, fontSize: 12, marginLeft: 5 }, stock: { color: colors.lime, fontSize: 10, fontWeight: '900', marginLeft: 'auto' }, priceRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 18 }, price: { color: colors.white, fontSize: 31, fontWeight: '900' }, oldPrice: { color: colors.muted, textDecorationLine: 'line-through', fontSize: 13 }, installments: { color: colors.purpleBright, fontSize: 11, marginTop: 3 }, divider: { height: 1, backgroundColor: colors.line, marginVertical: 22 }, sectionTitle: { color: colors.white, fontSize: 17, fontWeight: '900', marginBottom: 8 }, description: { color: colors.muted, fontSize: 13, lineHeight: 21 }, specs: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 18 }, spec: { width: '46%', flexDirection: 'row', alignItems: 'center', gap: 6 }, specText: { color: colors.white, fontSize: 11, fontWeight: '700' }, delivery: { backgroundColor: colors.surface, borderRadius: 15, padding: 14, marginTop: 22, flexDirection: 'row', gap: 11, alignItems: 'center' }, deliveryTitle: { color: colors.white, fontSize: 12, fontWeight: '900' }, deliveryText: { color: colors.muted, fontSize: 11, marginTop: 3 }, actions: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: 14, flexDirection: 'row', gap: 10, backgroundColor: '#100C1A', borderTopWidth: 1, borderTopColor: colors.line }, buy: { flex: 1, height: 51, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.lime }, buyText: { color: colors.background, fontSize: 14, fontWeight: '900' }, add: { width: 54, height: 51, borderRadius: 14, backgroundColor: colors.purpleBright, alignItems: 'center', justifyContent: 'center' },
});
