import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import Icon from '../components/Icon';
import BottomNav from '../components/BottomNav';
import { colors } from '../theme';

export default function ProfileScreen({ navigation, cartCount, user, onLogout }) {
  return <SafeAreaView style={styles.safeArea}><ScrollView contentContainerStyle={styles.content}><Text style={styles.kicker}>GAMECUBE ID</Text><Text style={styles.title}>Tu perfil</Text>{user ? <><View style={styles.profile}><View style={styles.avatar}><Icon name="account-circle" size={32} color={colors.background} /></View><View><Text style={styles.profileTitle}>{user.name}</Text><Text style={styles.profileSubtitle}>{user.email}</Text></View></View><Pressable style={styles.login} onPress={onLogout}><Icon name="logout-variant" size={20} color={colors.background} /><Text style={styles.loginText}>Cerrar sesión</Text></Pressable></> : <><View style={styles.profile}><View style={styles.avatar}><Icon name="account-circle-outline" size={32} color={colors.background} /></View><View><Text style={styles.profileTitle}>Aún no has iniciado sesión</Text><Text style={styles.profileSubtitle}>Guarda tus datos para comprar más rápido</Text></View></View><Pressable style={styles.login} onPress={() => navigation.navigate('Login')}><Icon name="login-variant" size={20} color={colors.background} /><Text style={styles.loginText}>Iniciar sesión</Text></Pressable><Pressable style={styles.register} onPress={() => navigation.navigate('Login')}><Icon name="account-plus-outline" size={20} color={colors.purpleBright} /><Text style={styles.registerText}>Crear una cuenta</Text></Pressable></>}<View style={styles.links}>{user?.role !== 'admin' && <Pressable style={styles.link} onPress={() => navigation.navigate(user ? 'OrderHistory' : 'Login')}><Icon name="receipt-long" size={23} color={colors.purpleBright} /><Text style={styles.linkText}>Historial de pedidos</Text><Icon name="chevron-right" size={20} color={colors.muted} /></Pressable>}<Pressable style={styles.link} onPress={() => navigation.navigate(user ? 'SupportChat' : 'Login')}><Icon name="lifebuoy" size={23} color={colors.purpleBright} /><Text style={styles.linkText}>Chat de soporte</Text><Icon name="chevron-right" size={20} color={colors.muted} /></Pressable><Pressable style={styles.link}><Icon name="help-circle-outline" size={23} color={colors.purpleBright} /><Text style={styles.linkText}>Centro de ayuda</Text><Icon name="chevron-right" size={20} color={colors.muted} /></Pressable></View></ScrollView><BottomNav active="profile" navigation={navigation} cartCount={cartCount} /></SafeAreaView>;
}

const styles = StyleSheet.create({ safeArea: { flex: 1, backgroundColor: colors.background }, content: { padding: 18, paddingBottom: 120 }, kicker: { color: colors.purpleBright, fontSize: 10, fontWeight: '900', letterSpacing: 1.4, marginTop: 12 }, title: { color: colors.white, fontSize: 32, fontWeight: '900', marginTop: 5 }, profile: { backgroundColor: colors.card, borderRadius: 17, padding: 16, flexDirection: 'row', alignItems: 'center', marginTop: 25 }, avatar: { width: 56, height: 56, borderRadius: 28, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center', marginRight: 13 }, profileTitle: { color: colors.white, fontSize: 14, fontWeight: '800' }, profileSubtitle: { color: colors.muted, fontSize: 11, marginTop: 5 }, login: { height: 49, borderRadius: 14, backgroundColor: colors.lime, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 15 }, loginText: { color: colors.background, fontSize: 13, fontWeight: '900' }, register: { height: 49, borderRadius: 14, borderWidth: 1, borderColor: colors.purpleBright, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 10 }, registerText: { color: colors.purpleBright, fontSize: 13, fontWeight: '900' }, links: { backgroundColor: colors.card, borderRadius: 17, paddingHorizontal: 16, marginTop: 24 }, link: { height: 61, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: colors.line }, linkText: { flex: 1, color: colors.white, fontSize: 13, fontWeight: '700', marginLeft: 12 } });
